ddnech/Mini_Project_3

projects/server/src/controllers/authController.js, projects/server/src/controllers/index.js, projects/server/src/index.js, projects/server/src/migrations/20230630030604-create-user.js, projects/server/src/models/index.js, projects/server/src/models/user.js, projects/server/src/routes/auth.js, projects/server/src/routes/index.js
adding user controller login user
=> login user controller

projects/server/src/controllers/authController.js, projects/server/src/middleware/validatorMiddleware/index.js, projects/server/src/migrations/20230630030604-create-user.js, projects/server/src/routes/auth.js, projects/server/src/routes/authRouter.js
update auth controller loginUser and registerUser
=> updating ath controller register and login

projects/server/src/Public/.gitignore, projects/server/src/controllers/authController.js, projects/server/src/controllers/index.js, projects/server/src/controllers/productController.js, projects/server/src/helper/index.js, projects/server/src/index.js, projects/server/src/middleware/multerMiddleware/product.js, projects/server/src/routes/index.js, projects/server/src/routes/productRouter.js
create folder for multer
create controller for create and update product
=> adding create and update product controller

projects/client/src/App.jsx, projects/client/src/component/footer.jsx, projects/client/src/component/header.jsx, projects/client/src/component/navbar.jsx, projects/client/src/page/home.jsx, projects/client/src/page/login.jsx, projects/client/src/page/signup.jsx, projects/client/src/store/index.js
- creating first mock up navbar, header, and footer.
- adding dependencies.
=> init landing page

projects/server/src/controllers/productController.js, projects/server/src/index.js, projects/server/src/middleware/validatorMiddleware/index.js, projects/server/src/migrations/20230630030703-create-category.js, projects/server/src/models/category.js, projects/server/src/routes/productRouter.js, projects/server/src/routes/userRouter.js
- add create and modify categories controller
- modify product's migrations and models
- add get all and user categories controller
=> feature: create and modify category (BE)

projects/client/src/App.jsx, projects/client/src/component/user/navbarDashboard.jsx, projects/client/src/page/userProfile.jsx
- adding new route for myprofile dashboard FE
- adding navbar for user dashboard menu
=> init user dashboard page

projects/client/src/component/user/myshop.jsx, projects/client/src/component/user/shopCategory.jsx, projects/client/src/component/user/shopIncome.jsx, projects/client/src/component/user/shopNew.jsx, projects/client/src/component/user/shopProduct.jsx, projects/client/src/page/userPurchase.jsx, projects/client/src/page/userShop.jsx
create folder for myshop component
=> create folder for myshop(FE)

projects/client/src/component/navbar.jsx, projects/client/src/component/user/shopNew.jsx
frontend page for create product
=> frontend component for create product user

projects/client/src/component/user/shopCategory.jsx, projects/client/src/component/user/signupUser.jsx
- create category (FE)
- modify category (FE)
=> feature: create and modify category

projects/client/src/component/user/storeProduct.jsx
create product view on user dashboard
=> create page for product dasboard

projects/client/src/component/user/contentStore.jsx, projects/client/src/component/user/storeProduct.jsx
enhance response when product is not found
=> enhancing view product

projects/client/src/component/user/storeProduct.jsx, projects/client/tailwind.config.js
adding pagination on view user product
=> adding pagination

projects/client/src/component/user/storeProduct.jsx
=> complete pagination feature (FE)

projects/client/src/component/user/storeCategory.jsx
=> optimize category (FE)

projects/server/src/controllers/productController.js, projects/server/src/models/product.js, projects/server/src/models/user.js, projects/server/src/routes/productRouter.js
- adding new relation between user and product as a seller
- create getAllProduct controller
=> redefine user and product associate

projects/server/src/controllers/transactionController.js, projects/server/src/middleware/validatorMiddleware/index.js, projects/server/src/routes/userRouter.js
creating route, controller, validator to addToCart
=> creating addToCart controller (BE)

projects/server/src/controllers/productController.js
Add isActive to where query for getAllProduct controller
=> adding where isActive for product

projects/client/src/component/oneProduct.jsx, projects/client/src/component/user/editProduct.jsx, projects/client/src/component/user/storeProduct.jsx, projects/client/src/page/modifyProduct.jsx
client side push for modify product
=> client side push for modify product

projects/client/src/component/cardProduct.jsx, projects/client/src/page/home.jsx
creating init view product (FE)
=> init view product (FE)

projects/client/src/component/cardProduct.jsx, projects/client/src/component/navbar.jsx, projects/client/src/component/user/storeProduct.jsx, projects/client/src/page/home.jsx
fixing pagination and search filter feature
=> fixing pagination view product landing page

projects/server/src/controllers/transactionController.js, projects/server/src/routes/userRouter.js
creating controllers for cart and transaction features
=> BE for cart and transaction

projects/server/src/controllers/transactionController.js, projects/server/src/migrations/20230630031315-create-order-item.js, projects/server/src/models/order_item.js
- revised migration cart
- revised checkout controller
=> revised migration for cart and revised checkout controller

projects/client/src/component/oneProductSeller.jsx, projects/client/src/component/user/contentCart.jsx, projects/client/src/component/user/editProduct.jsx, projects/client/src/page/modifyProduct.jsx
=> init cart page and fixing minor issues

projects/client/src/component/navbar.jsx, projects/client/src/component/oneProductBuyer.jsx, projects/client/src/component/user/contentCart.jsx, projects/client/src/component/user/contentStore.jsx, projects/client/src/component/user/storeProduct.jsx, projects/client/src/component/user/storeTransaction.jsx, projects/client/src/component/user/topSellingSeller.jsx, projects/client/src/page/home.jsx
=> feature: user transaction

projects/client/src/component/cardProduct.jsx, projects/client/src/component/topselling.jsx, projects/server/src/controllers/productController.js, projects/server/src/controllers/userController.js, projects/server/src/routes/productRouter.js
top selling landing page and minor fixing
=> feature: top selling landing page and minor fixing

projects/server/src/seeders/20230710132955-create-category.js
create category seeders for default category
=> create category seeders

projects/client/src/component/cardProduct.jsx, projects/client/src/component/footer.jsx, projects/client/src/component/header.jsx, projects/client/src/component/navbar.jsx, projects/client/src/component/topselling.jsx, projects/client/src/component/user/contentCart.jsx, projects/client/src/component/user/contentPurchase.jsx, projects/client/src/component/user/loginUser.jsx, projects/client/src/component/user/profileDetails.jsx, projects/client/src/component/user/signupUser.jsx, projects/client/src/component/user/storeCategory.jsx, projects/client/src/component/user/storeIncome.jsx, projects/client/src/component/user/storeNew.jsx, projects/client/src/component/user/storeProduct.jsx, projects/client/src/component/user/storeTransaction.jsx, projects/client/src/component/user/topSellingSeller.jsx, projects/client/src/page/signup.jsx
=> fixing frontend layouting
